### ISSUE TITLE
Incorrect directory?

### ISSUE THREAD

**Issue by rayterrill** [vendasta/setup-new-computer-script#12]
https://github.com/vendasta/setup-new-computer-script/blob/50ac22ebbbe86752c670d82a99a38ae166bd7c27/setup-new-computer.sh#L616

This should probably be .ssh?

**Comment by rayterrill** [comment]
Appreciate you sharing this script - it's so awesome. :)

**Comment by joelkesler** [comment]
Hello! In our case, we are using the go programming language, and that is the default directory for go workspace.

https://go.dev/doc/gopath_code#GOPATH

If you aren't using go in your workflow, you probably want to remove that from your version of the setup-script :)
