### ISSUE TITLE
Idempotency

### ISSUE THREAD

**Issue by jonchurch** [vendasta/setup-new-computer-script#2]
Is the script idempotent? Would be great if a user could run this multiple times successfully, in case something goes wrong or it is accidentally killed. 

I'm not on  a mac and haven't run it myself, but doing a quick find there's at least the `mkdir ~/go` which would fail if that dir already exists. Could be `mkdir -p`. Not sure if the script gracefully handles errors like that.

**Comment by joelkesler** [comment]
> Would be great if a user could run this multiple times successfully, in case something goes wrong or it is accidentally killed.

You should be able to. While developing it I have run it multiple times on my own computer and on clean install Mac OS VMs. I have not noticed problems myself.

Besides the mkdir bug, the main thing I noticed (that I need to fix) is that I need to check for Chrome, Slack, etc before installing them with brew. 

Brew is not always smart enough to check if the app exists before downloading and trying to install. This doesn't break the script, it just wastes time.
